using System;
using System.IO;
using System.Threading;
using LibVLCSharp.Shared;
using NAudio.Wave;
using LoggerService;
using RTLSDR.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Runtime.InteropServices;
using System.Collections.Concurrent;

namespace RTLSDR.Audio
{
    public class VLCSoundAudioPlayer : IRawAudioPlayer
    {
        private MediaPlayer? _mediaPlayer;
        private Media? _media;
        private LibVLC? _libVLC;
        private VLCMediaInput _pcmInput = new VLCMediaInput();
        private AudioDataDescription? _audioDescription;
        private ILoggingService? _loggingService;

        private void InitCore()
        {
            if (_libVLC == null)
            {
                Core.Initialize();
                _libVLC = new LibVLC(
                    "--quiet",
                    "--no-stats",
                    "--verbose=0"  // "--verbose=2"
                );

                // !! code generated by AI, app crash when uncommented
                //if (_loggingService != null)
                //{
                //    _libVLC.Log += (s, e) => _loggingService.Debug($"libvlc: [{e.Level}] {e.Module}: {e.Message}");
                //}
            }
        }

        public void InitUrl(string url, ILoggingService loggingService, string[]? mediaOptions = null)
        {
            _loggingService = loggingService;

            InitCore();

            _media = new Media(_libVLC, url, FromType.FromLocation, mediaOptions);

            _mediaPlayer = new MediaPlayer(_media);
            _mediaPlayer.Volume = 100;
        }

        public void Init(AudioDataDescription audioDescription, ILoggingService loggingService, string[]? mediaOptions = null)
        {
            _loggingService = loggingService;

            _loggingService.Info($"Initializing VLC audio player with description: {audioDescription}");

            InitCore();

            _audioDescription = audioDescription;


            if (mediaOptions == null)
            {
                // no media options provided, use _pcmInput defaults based on audio description
                mediaOptions = new[]
                {
                    ":demux=rawaud",
                    $":rawaud-channels={audioDescription.Channels}",
                    $":rawaud-samplerate={audioDescription.SampleRate}",
                    ":live-caching=50",
                    ":file-caching=50",
                    ":clock-jitter=0",
                    ":clock-synchro=0",
                    ":rawaud-fourcc=s16l"
                };
            }

            _media = new Media(_libVLC, _pcmInput, mediaOptions);

            _mediaPlayer = new MediaPlayer(_media);
            _mediaPlayer.Volume = 100;
        }

        public AudioDataDescription? GetAudioDataDescription()
        {
            return _audioDescription;
        }

        public void Play()
        {
            _mediaPlayer?.Play();
        }

        public void AddData(byte[] data)
        {
            _pcmInput.PushData(data);
        }

        public void Stop()
        {
            _pcmInput.Close();
            _mediaPlayer?.Stop();
        }

        public void ClearBuffer()
        {
            _pcmInput.ClearBuffer();
        }

        public void SetMaxBufferSize(int sizeInBytes)
        {
            _pcmInput.MaxDataRequestSize = (uint)sizeInBytes;
        }
    }
}

